import type { Node, Edge } from "reactflow";

import { ArduinoUnoRuntime } from "../boards/ArduinoUnoRuntime";
import { Avr8jsRunner } from "./Avr8jsRunner";
import { SimulationClock } from "./SimulationClock";

import type {
  SimulationEngineOptions,
  SimulationStatus,
  ArduinoUnoRuntimeState,
  SimulationDiagnostics,
  SimulationTrace,
  SimulationTraceStep,
} from "../types/simulator.types";

import {
  createCircuitGraph,
  type CircuitEdgeData,
} from "../circuit/CircuitGraph";

import {
  NetlistBuilder,
  type Netlist,
} from "../circuit/NetlistBuilder";

import {
  DigitalCircuitSolver,
  type DigitalCircuitState,
} from "../electrical/DigitalCircuitSolver";

import {
  CurrentFlowSolver,
  type CurrentFlowState,
} from "../electrical/CurrentFlowSolver";

import {
  DigitalInputSolver,
  type DigitalInputState,
} from "../electrical/DigitalInputSolver";

import {
  PowerRailSolver,
  type PowerRailState,
} from "../electrical/PowerRailSolver";

import {
  AnalogCircuitSolver,
  type AnalogInputState,
} from "../electrical/AnalogCircuitSolver";

import { intelHexToProgram } from "./IntelHex";
import {
  Lcd1602Runtime,
} from "../components/Lcd1602Runtime";
import {
  I2cPeripheralEventHandler,
} from "../components/I2cPeripheralEventHandler";
import {
  Ssd1306Runtime,
  Ssd1306SpiBridge,
  Ssd1306SoftwareSpiDecoder,
} from "../components/Ssd1306Runtime";
import { NeoPixelRuntime } from "../components/NeoPixelRuntime";
import { Ds1307Runtime } from "../components/Ds1307Runtime";
import {
  clearKeypadContacts,
  getKeypadContacts,
} from "../electrical/KeypadInputState";

/* =========================================================
   ENGINE OPTIONS
========================================================= */

export interface CircuitSimulationEngineOptions
  extends SimulationEngineOptions {
  arduinoNodeId?: string;
  nodes?: Node[];
  edges?: Edge<CircuitEdgeData>[];
}

/* =========================================================
   ENGINE
========================================================= */

function createPinKeyForSimulation(nodeId: string, pinId: string): string {
  return nodeId + ":" + pinId;
}

function optionsFrequency(
  options: SimulationEngineOptions,
): number {
  return options.config?.frequency ?? 16_000_000;
}

export class SimulationEngine {
  private status: SimulationStatus = "idle";

  private readonly arduino =
    new ArduinoUnoRuntime();

  private readonly avr =
    new Avr8jsRunner();

  private readonly clock =
    new SimulationClock();

  private readonly netlistBuilder =
    new NetlistBuilder();

  private readonly digitalSolver =
    new DigitalCircuitSolver();

  private readonly digitalInputSolver =
    new DigitalInputSolver();

  private readonly currentFlowSolver =
    new CurrentFlowSolver();

  private readonly powerRailSolver =
    new PowerRailSolver();

  private readonly analogCircuitSolver =
    new AnalogCircuitSolver();

  private readonly options: SimulationEngineOptions;

  private netlist: Netlist | null = null;

  private circuitNodes: Node[] = [];

  private circuitEdges: Edge<CircuitEdgeData>[] =
    [];

  private digitalState: DigitalCircuitState = {
    pinLevels: new Map(),
    conflicts: [],
  };

  private digitalInputState: DigitalInputState = {
    pinLevels: new Map(),
    conflicts: [],
    floatingPins: [],
  };

  private currentFlowState: CurrentFlowState = {
    wireStates: {},
    activeNets: new Set(),
    activeComponents: new Set(),
    componentBrightness: {},
    componentCurrentMa: {},
    componentVoltageDrop: {},
    conflicts: [],
  };

  private powerState: PowerRailState = {
    netVoltages: {},
    pinVoltages: {},
    sourceNets: new Map(),
    groundNets: new Set(),
    conflicts: [],
  };

  private analogState: AnalogInputState = {
    pinVoltages: new Map(),
    pinValues: new Map(),
    digitalOutputs: new Map(),
    sensorVoltages: new Map(),
    sensorResistanceOhms: new Map(),
    conflicts: [],
  };

  private firmwareLoaded = false;

  private readonly cyclesPerFrame: number;
  private simulatedCycles = 0;
  private frameCount = 0;
  private activeTrace: SimulationTrace | undefined;

  /**
   * Last observed TRIG level for each HC-SR04.
   * The AVR runner reports GPIO edges while executing the real firmware.
   */
  private readonly ultrasonicTriggerLevels =
    new Map<string, 0 | 1>();

  /** Start cycle of the current HIGH pulse for each connected servo signal. */
  private readonly servoPulseStarts =
    new Map<string, number>();

  /**
   * Servo control pulses are generated by Servo.h through real AVR GPIO
   * transitions. Keep the decoder tied to the simulator clock rather than
   * assuming 16 MHz so the same runtime remains correct if the board clock
   * configuration changes.
   */
  private getServoClockFrequencyHz(): number {
    return this.options.config?.frequency ?? 16_000_000;
  }

  private isServoPowered(
    component: Netlist["components"][number],
  ): boolean {
    const vcc = component.terminals["V+"];
    const gnd = component.terminals.GND;

    if (!vcc || !gnd) {
      return false;
    }

    const vccVoltage = this.powerState.netVoltages[vcc];
    const gndVoltage = this.powerState.netVoltages[gnd];

    if (
      typeof vccVoltage !== "number" ||
      typeof gndVoltage !== "number"
    ) {
      return false;
    }

    /*
     * Prefer the explicit rail topology when available. This prevents a
     * floating/ambiguous net from being treated as a powered servo just
     * because a stale pin voltage exists.
     */
    const hasPositiveSource =
      this.powerState.sourceNets.has(vcc) ||
      vccVoltage >= 3;

    const hasGroundReference =
      this.powerState.groundNets.has(gnd) ||
      Math.abs(gndVoltage) < 0.05;

    return (
      hasPositiveSource &&
      hasGroundReference &&
      vccVoltage - gndVoltage >= 3
    );
  }

  private readonly lcdRuntimes =
    new Map<string, Lcd1602Runtime>();

  private readonly ssd1306Runtimes =
    new Map<string, Ssd1306Runtime>();

  private readonly neoPixelRuntimes =
    new Map<string, NeoPixelRuntime>();

  private readonly ds1307Runtimes =
    new Map<string, Ds1307Runtime>();

  /**
   * PIR timing is kept in simulated AVR cycles so the sensor follows
   * the same clock as delay()/millis()/micros() and remains deterministic.
   */
  private readonly pirRuntime =
    new Map<
      string,
      {
        lastTriggerId: number;
        highUntilCycle: number;
        inhibitUntilCycle: number;
      }
    >();

  /*
   * Cache the last firmware-driven GPIO level for parallel LCD pins.
   *
   * The LCD latches its bus on E's falling edge. Reading AVR registers
   * again inside that callback is fragile when several GPIO changes are
   * produced by the same firmware operation. The callback already gives
   * us the exact level that changed, so keep that electrical bus state
   * and sample the cached values when E falls.
   */
  private readonly parallelLcdGpioLevels =
    new Map<string, 0 | 1>();

  private lcdI2cHandler:
    I2cPeripheralEventHandler | null = null;

  private ssd1306SpiBridge:
    Ssd1306SpiBridge | null = null;

  private ssd1306SoftwareSpi:
    Ssd1306SoftwareSpiDecoder | null = null;

  constructor(
    options: SimulationEngineOptions = {},
  ) {
    this.options = options;

    const frequency =
      options.config?.frequency ??
      16_000_000;

    this.cyclesPerFrame = Math.max(
      1,
      Math.floor(frequency / 60),
    );
  }

  getStatus(): SimulationStatus {
    return this.status;
  }

  private detectParallelLcdMode(
    node: Node,
  ): "4bit" | "8bit" {
    const configured =
      node.data?.lcdMode;

    if (
      typeof configured === "string" &&
      configured.toLowerCase() === "8bit"
    ) {
      return "8bit";
    }

    const graph =
      createCircuitGraph(
        this.circuitNodes,
        this.circuitEdges,
      );

    const wiredPins = new Set<string>();

    for (const wire of graph.wires) {
      for (const ref of [wire.source, wire.target]) {
        if (ref.nodeId === node.id) {
          wiredPins.add(
            ref.pinId.toUpperCase(),
          );
        }
      }
    }

    return ["D0", "D1", "D2", "D3"].some(
      (pin) => wiredPins.has(pin),
    )
      ? "8bit"
      : "4bit";
  }

  private isLcdPowered(
    component: {
      terminals: Record<string, string | null>;
    },
  ): boolean {
    const vcc =
      component.terminals.VDD ??
      component.terminals.VCC ??
      null;

    const gnd =
      component.terminals.VSS ??
      component.terminals.GND ??
      null;

    return Boolean(
      vcc &&
      gnd &&
      (
        this.powerState.sourceNets.has(vcc) ||
        this.powerState.netVoltages[vcc] === 5 ||
        this.powerState.netVoltages[vcc] === 3.3
      ) &&
      this.powerState.groundNets.has(gnd),
    );
  }

  private isLcdI2cConnected(
    componentId: string,
  ): boolean {
    if (!this.netlist) {
      return false;
    }

    const component =
      this.netlist.components.find(
        (item) => item.id === componentId,
      );

    if (!component) {
      return false;
    }

    const netHasArduinoPin = (
      netId: string | null | undefined,
      pinName: string,
    ): boolean => {
      if (!netId) {
        return false;
      }

      return (
        this.netlist!.netToPins
          .get(netId)
          ?.some(
            (pin) =>
              pin.pinId.toUpperCase() ===
              pinName.toUpperCase(),
          ) ?? false
      );
    };

    /*
     * Arduino UNO hardware TWI is on A4/SDA and A5/SCL.
     * Require the actual circuit topology to connect both lines.
     * VCC/GND must also exist on the LCD component.
     */
    return (
      netHasArduinoPin(
        component.terminals.SDA,
        "A4",
      ) &&
      netHasArduinoPin(
        component.terminals.SCL,
        "A5",
      ) &&
      this.isLcdPowered(component)
    );
  }

  private getConnectedArduinoGpioPin(
    componentId: string,
    terminal: string,
  ): string | null {
    if (!this.netlist) return null;

    const component = this.netlist.components.find(
      (item) => item.id === componentId,
    );
    const netId = component?.terminals[terminal];

    if (!netId) return null;

    const refs = this.netlist.netToPins.get(netId) ?? [];

    for (const ref of refs) {
      if (!/^(?:D|A)\d+$/i.test(ref.pinId)) continue;

      const node = this.circuitNodes.find(
        (candidate) => candidate.id === ref.nodeId,
      );

      const type = String(
        node?.data?.componentType ??
          node?.type ??
          "",
      ).toLowerCase();

      if (
        type === "arduino-uno" ||
        type === "arduino"
      ) {
        return ref.pinId.toUpperCase();
      }
    }

    return null;
  }

  private isDs1307I2cConnected(
    componentId: string,
  ): boolean {
    if (!this.netlist) {
      return false;
    }

    const component =
      this.netlist.components.find(
        (item) => item.id === componentId,
      );

    if (!component) {
      return false;
    }

    const netHasArduinoPin = (
      netId: string | null | undefined,
      pinName: string,
    ): boolean => {
      if (!netId) {
        return false;
      }

      return (
        this.netlist!.netToPins
          .get(netId)
          ?.some(
            (pin) =>
              pin.pinId.toUpperCase() ===
              pinName.toUpperCase(),
          ) ?? false
      );
    };

    return (
      netHasArduinoPin(component.terminals.SDA, "A4") &&
      netHasArduinoPin(component.terminals.SCL, "A5") &&
      this.isDs1307Powered(component)
    );
  }

  private isDs1307Powered(
    component: Netlist["components"][number],
  ): boolean {
    const vcc = component.terminals.VCC;
    const gnd = component.terminals.GND;

    if (!vcc || !gnd) {
      return false;
    }

    const vccVoltage =
      this.powerState.netVoltages[vcc];

    const gndVoltage =
      this.powerState.netVoltages[gnd];

    const hasPositiveSource =
      this.powerState.sourceNets.has(vcc) ||
      (typeof vccVoltage === "number" &&
        vccVoltage >= 3);

    const hasGroundReference =
      this.powerState.groundNets.has(gnd) ||
      (typeof gndVoltage === "number" &&
        Math.abs(gndVoltage) < 0.05);

    if (!hasPositiveSource || !hasGroundReference) {
      return false;
    }

    /*
     * PowerRailSolver may know a rail is sourced/grounded without
     * materializing a numeric voltage for every net. Do not reject a
     * physically valid DS1307 connection just because one voltage entry
     * is absent. When both voltages are available, still enforce the real
     * minimum supply differential.
     */
    if (
      typeof vccVoltage === "number" &&
      typeof gndVoltage === "number"
    ) {
      return vccVoltage - gndVoltage >= 3;
    }

    return true;
  }

  private updateDs1307PowerStates(
    cycle: number,
  ): void {
    if (!this.netlist) {
      return;
    }

    for (const component of this.netlist.components) {
      const runtime =
        this.ds1307Runtimes.get(component.id);

      if (!runtime) {
        continue;
      }

      runtime.setPowered(
        this.isDs1307Powered(component),
      );

      runtime.advanceToCycle(cycle);
    }

    const runtimeState =
      this.arduino.getState().ds1307States;

    for (const [id, runtime] of this.ds1307Runtimes) {
      const state = runtime.getState(cycle);
      runtimeState[id] = {
        id,
        powered: state.powered,
        year: state.year,
        month: state.month,
        day: state.day,
        hour: state.hour,
        minute: state.minute,
        second: state.second,
        dayOfWeek: state.dayOfWeek,
        sqwMode: state.sqwMode,
        sqwLevel: state.sqwLevel,
      };
    }
  }

  private resolveDs1307SqwOutputs(
    cycle: number,
  ): Map<string, 0 | 1> {
    const outputs = new Map<string, 0 | 1>();

    if (!this.netlist) {
      return outputs;
    }

    for (const component of this.netlist.components) {
      const runtime =
        this.ds1307Runtimes.get(component.id);

      const sqwNet =
        component.terminals.SQW;

      if (!runtime || !sqwNet) {
        continue;
      }

      runtime.advanceToCycle(cycle);
      outputs.set(
        sqwNet,
        runtime.getSqwLevel(cycle),
      );
    }

    return outputs;
  }

  private updateSsd1306PowerStates(): void {
    if (!this.netlist) {
      return;
    }

    for (const component of this.netlist.components) {
      const runtime =
        this.ssd1306Runtimes.get(component.id);

      if (!runtime) {
        continue;
      }

      const vin = component.terminals.VIN;
      const gnd = component.terminals.GND;

      const powered =
        typeof vin === "string" &&
        typeof gnd === "string" &&
        (
          this.powerState.sourceNets.has(vin) ||
          (this.powerState.netVoltages[vin] ?? 0) >= 2.5
        ) &&
        (
          this.powerState.groundNets.has(gnd) ||
          Math.abs(this.powerState.netVoltages[gnd] ?? 999) < 0.05
        );

      runtime.setPowered(powered);
    }
  }


  /**
   * Resolve a PIR sensor's electrical output.
   *
   * The Wokwi element is presentation-only; the simulator owns the
   * functional model. OUT becomes a real digital source on the sensor's
   * net, so Arduino digitalRead() receives the same level as it would
   * from a physical HC-SR501.
   */
  private resolvePirOutputs(): Map<string, 0 | 1> {
    const outputs = new Map<string, 0 | 1>();
    const runtimeState = this.arduino.getState().pirStates;
    const frequency =
      this.options.config?.frequency ?? 16_000_000;
    const now = this.simulatedCycles;

    for (const component of this.netlist?.components ?? []) {
      const node = this.circuitNodes.find(
        (candidate) => candidate.id === component.id,
      );

      if (!node) {
        continue;
      }

      const type = String(
        node.data?.componentType ?? node.type ?? "",
      ).toLowerCase();

      if (
        type !== "pir" &&
        type !== "pir-motion-sensor" &&
        type !== "pir-motion"
      ) {
        continue;
      }

      const vccNet =
        component.terminals.VCC ??
        component.terminals.vcc;

      const gndNet =
        component.terminals.GND ??
        component.terminals.gnd;

      const outNet =
        component.terminals.OUT ??
        component.terminals.out;

      const powered =
        typeof vccNet === "string" &&
        typeof gndNet === "string" &&
        (
          this.powerState.sourceNets.has(vccNet) ||
          (this.powerState.netVoltages[vccNet] ?? 0) >= 2.5
        ) &&
        (
          this.powerState.groundNets.has(gndNet) ||
          Math.abs(this.powerState.netVoltages[gndNet] ?? 999) < 0.05
        );

      const props =
        node.data?.props &&
        typeof node.data.props === "object"
          ? (node.data.props as Record<string, unknown>)
          : {};

      const readPositiveNumber = (
        value: unknown,
        fallback: number,
      ): number => {
        const number = Number(value);
        return Number.isFinite(number) && number >= 0
          ? number
          : fallback;
      };

      const delayTimeSec = Math.max(
        0,
        Math.min(
          60,
          readPositiveNumber(
            node.data?.pirDelayTime ??
              props.delayTime,
            5,
          ),
        ),
      );

      const inhibitTimeSec = Math.max(
        0,
        Math.min(
          60,
          readPositiveNumber(
            node.data?.pirInhibitTime ??
              props.inhibitTime,
            1.2,
          ),
        ),
      );

      const retrigger =
        !(
          String(
            node.data?.pirRetrigger ??
              props.retrigger ??
              "",
          ).toLowerCase() === "0" ||
          String(
            node.data?.pirRetrigger ??
              props.retrigger ??
              "",
          ).toLowerCase() === "false"
        );

      const delayCycles = Math.max(
        1,
        Math.round(delayTimeSec * frequency),
      );

      const inhibitCycles = Math.max(
        0,
        Math.round(inhibitTimeSec * frequency),
      );

      const triggerId = Number(
        node.data?.pirMotionTrigger ?? 0,
      ) || 0;

      const state =
        this.pirRuntime.get(node.id) ?? {
          // Start from zero so the first UI motion event (triggerId=1)
          // is never swallowed when it happens before the first tick.
          lastTriggerId: 0,
          highUntilCycle: 0,
          inhibitUntilCycle: 0,
        };

      /*
       * A trigger is an edge/event, not a persistent boolean. The UI
       * increments pirMotionTrigger each time "Simulate Motion" is clicked.
       */
      if (
        triggerId !== state.lastTriggerId &&
        triggerId > 0 &&
        powered
      ) {
        if (now >= state.inhibitUntilCycle) {
          const nextHighUntil =
            now + delayCycles;

          if (
            now < state.highUntilCycle &&
            retrigger
          ) {
            state.highUntilCycle = Math.max(
              state.highUntilCycle,
              nextHighUntil,
            );
          } else {
            state.highUntilCycle = nextHighUntil;
          }

          /*
           * Inhibit starts when OUT returns LOW, matching the documented
           * HC-SR501 behavior rather than blocking motion while OUT is HIGH.
           */
          state.inhibitUntilCycle = 0;
        }

        state.lastTriggerId = triggerId;
      } else if (triggerId !== state.lastTriggerId) {
        state.lastTriggerId = triggerId;
      }

      const outputHigh =
        powered &&
        now < state.highUntilCycle;

      if (
        powered &&
        !outputHigh &&
        state.highUntilCycle > 0 &&
        state.inhibitUntilCycle === 0 &&
        now >= state.highUntilCycle
      ) {
        state.inhibitUntilCycle =
          state.highUntilCycle + inhibitCycles;
      }

      const motion = outputHigh;

      if (typeof outNet === "string") {
        outputs.set(outNet, outputHigh ? 1 : 0);
      }

      runtimeState[node.id] = {
        id: node.id,
        motion,
        outputHigh,
        powered,
        delayTimeSec,
        inhibitTimeSec,
        retrigger,
        lastTriggerId: state.lastTriggerId,
      };

      this.pirRuntime.set(node.id, state);
    }

    return outputs;
  }

  private emit(): void {
    this.options.onStateChange?.(
      this.arduino.getState(),
    );
  }

  private setStatus(
    status: SimulationStatus,
  ): void {
    this.status = status;
    this.emit();
  }

  /**
   * Build the simulator topology from the
   * actual React Flow circuit.
   */
  setCircuit(
    nodes: Node[],
    edges: Edge[],
  ): void {
    this.circuitNodes = nodes;

    this.circuitEdges =
      edges as Edge<CircuitEdgeData>[];

    this.netlist =
      this.netlistBuilder.build(
        createCircuitGraph(
          nodes,
          this.circuitEdges,
        ),
      );

    this.activeTrace = undefined;
    this.ultrasonicTriggerLevels.clear();
    this.servoPulseStarts.clear();
    this.lcdRuntimes.clear();
    this.ssd1306Runtimes.clear();
    this.neoPixelRuntimes.clear();
    this.ds1307Runtimes.clear();
    this.pirRuntime.clear();
    this.parallelLcdGpioLevels.clear();
    this.lcdI2cHandler = null;
    this.ssd1306SpiBridge = null;
    this.ssd1306SoftwareSpi = null;

    for (const node of nodes) {
      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (
        type === "lcd1602" ||
        type === "lcd-1602" ||
        type === "lcd1602-full"
      ) {
        const mode = this.detectParallelLcdMode(node);
        this.lcdRuntimes.set(
          node.id,
          new Lcd1602Runtime(node.id, mode),
        );
      } else if (
        type === "lcd1602-i2c" ||
        type === "lcd1602_i2c" ||
        type === "lcd-i2c"
      ) {
        const props =
          node.data?.props &&
          typeof node.data.props === "object"
            ? (node.data.props as Record<string, unknown>)
            : {};

        const configuredAddress =
          props.address ??
          props.i2cAddress ??
          node.data?.i2cAddress;

        const address =
          configuredAddress === undefined
            ? undefined
            : Number(configuredAddress);

        this.lcdRuntimes.set(
          node.id,
          new Lcd1602Runtime(
            node.id,
            "i2c",
            address !== undefined && Number.isFinite(address)
              ? address
              : undefined,
          ),
        );
      } else if (type === "ssd1306") {
        this.ssd1306Runtimes.set(
          node.id,
          new Ssd1306Runtime(node.id),
        );
      } else if (type === "neopixel") {
        this.neoPixelRuntimes.set(
          node.id,
          new NeoPixelRuntime(
            node.id,
            optionsFrequency(this.options),
          ),
        );
      } else if (
        type === "ds1307" ||
        type === "rtc-ds1307" ||
        type === "rtc"
      ) {
        const props =
          node.data?.props &&
          typeof node.data.props === "object"
            ? (node.data.props as Record<string, unknown>)
            : {};

        this.ds1307Runtimes.set(
          node.id,
          new Ds1307Runtime(
            node.id,
            props.initTime ?? node.data?.initTime,
            optionsFrequency(this.options),
          ),
        );
      }
    }

    this.arduino.getState().buzzerStates = {};
    this.arduino.getState().ultrasonicStates = {};
    this.arduino.getState().lcdStates = {};
    this.arduino.getState().ssd1306States = {};
    this.arduino.getState().neopixelStates = {};
    this.arduino.getState().ds1307States = {};
    this.arduino.getState().sevenSegmentStates = {};
  }

  /**
   * Update live component state without rebuilding topology.
   *
   * This is used for interactive controls such as a pushbutton:
   * the wire graph stays the same, while the component's pressed
   * state changes while the simulation is already running.
   */
  updateNodes(nodes: Node[]): void {
    this.circuitNodes = nodes;
  }

  /**
   * Load the real HEX output produced by
   * Arduino CLI.
   */
  loadHex(hex: string): void {
    const program =
      intelHexToProgram(hex);

    if (program.length === 0) {
      throw new Error(
        "Compiled firmware is empty.",
      );
    }

    this.arduino.reset();
    this.servoPulseStarts.clear();
    this.parallelLcdGpioLevels.clear();

    this.avr.loadProgram(
      program,
      this.arduino,
    );

    this.avr.setSerialByteHandler((value) => {
      this.arduino.appendSerialOutput(value);
    });

    for (const lcd of this.lcdRuntimes.values()) {
      lcd.reset(
        lcd.getState().mode,
        lcd.getState().i2cAddress,
      );
    }

    for (const oled of this.ssd1306Runtimes.values()) {
      oled.reset();
    }

    for (const pixel of this.neoPixelRuntimes.values()) {
      pixel.reset();
    }

    for (const rtc of this.ds1307Runtimes.values()) {
      const initialEpoch = rtc.getEpochMs();
      rtc.reset(
        new Date(initialEpoch).toISOString(),
        optionsFrequency(this.options),
      );
    }

    const lcdI2cPeripherals = () =>
      Array.from(this.lcdRuntimes.values());

    this.lcdI2cHandler =
      new I2cPeripheralEventHandler(
        lcdI2cPeripherals,
        this.avr.getTwi()!,
        (display) =>
          this.isLcdI2cConnected(display.id),
        () =>
          Array.from(this.ds1307Runtimes.values()),
        (rtc) =>
          this.isDs1307I2cConnected(rtc.id),
      );

    this.avr.setTwiEventHandler(
      this.lcdI2cHandler,
    );

    this.ssd1306SpiBridge =
      new Ssd1306SpiBridge(
        () => Array.from(this.ssd1306Runtimes.values()),
        (pin) => this.avr.getGpioLevel(pin),
        (display, terminal) =>
          this.getConnectedArduinoGpioPin(
            display.id,
            terminal,
          ),
      );

    this.ssd1306SoftwareSpi =
      new Ssd1306SoftwareSpiDecoder(
        () => Array.from(this.ssd1306Runtimes.values()),
        (pin) => this.avr.getGpioLevel(pin),
        (display, terminal) =>
          this.getConnectedArduinoGpioPin(
            display.id,
            terminal,
          ),
      );

    const spi = this.avr.getSpi();

    if (spi) {
      spi.onByte = (value) => {
        this.ssd1306SpiBridge?.transfer(value);

        const cpu = this.avr.getCPU();
        if (cpu) {
          cpu.addClockEvent(
            () => spi.completeTransfer(0),
            spi.transferCycles,
          );
        }
      };
    }

    this.digitalState = {
      pinLevels: new Map(),
      conflicts: [],
    };

    this.currentFlowState = {
      wireStates: {},
      activeNets: new Set(),
      activeComponents: new Set(),
      componentBrightness: {},
      componentCurrentMa: {},
      componentVoltageDrop: {},
      conflicts: [],
    };

    this.digitalInputState = {
      pinLevels: new Map(),
      conflicts: [],
      floatingPins: [],
    };

    this.powerState = {
      netVoltages: {},
      pinVoltages: {},
      sourceNets: new Map(),
      groundNets: new Set(),
      conflicts: [],
    };

    this.analogState = {
      pinVoltages: new Map(),
      pinValues: new Map(),
      digitalOutputs: new Map(),
      sensorVoltages: new Map(),
      sensorResistanceOhms: new Map(),
      conflicts: [],
    };

    this.firmwareLoaded = true;
    this.simulatedCycles = 0;
    this.frameCount = 0;
    this.refreshDiagnostics();
    this.setStatus("idle");
  }

  start(): void {
    if (this.clock.isRunning()) {
      return;
    }

    if (!this.netlist) {
      throw new Error(
        "Circuit topology has not been built.",
      );
    }

    /*
     * Firmware is optional for power-only simulation.
     *
     * With an empty sketch the Uno power rails still exist:
     * 5V, 3.3V, IOREF and GND are available as soon as Run
     * starts. If firmware was loaded, AVR8JS is also executed.
     */
    this.setStatus("running");
    this.clock.start(() => this.tick());
  }

  private tick(): void {
    try {
      this.frameCount += 1;
      this.simulatedCycles += this.cyclesPerFrame;
      /*
       * The circuit is resolved twice around AVR execution:
       *
       *   circuit -> power -> input -> PINx
       *                         |
       *                         v
       *                      AVR8JS
       *                         |
       *                         v
       *                  GPIO outputs/PWM
       *                         |
       *                         v
       *                final circuit solve
       *
       * This is what makes digitalRead() a real firmware read of
       * the simulated electrical circuit rather than a JavaScript
       * shortcut.
       */
      if (this.netlist) {
        const preRunDrivers =
          this.arduino.getDigitalDrivers();

        this.powerState =
          this.powerRailSolver.solve(
            this.netlist,
            this.arduino.getPowerDrivers(),
            preRunDrivers,
            this.circuitNodes,
          );

        this.updateSsd1306PowerStates();
        this.updateNeoPixelPowerStates();
        this.updateDs1307PowerStates(
          this.simulatedCycles,
        );

        /*
         * Resolve analog voltages before AVR execution.
         *
         * A potentiometer is an electrical component with VCC/GND
         * and a wiper output. The solver determines the voltage at
         * SIG; the AVR runner later converts that voltage through
         * the ATmega328P ADC registers used by analogRead().
         */
        this.analogState =
          this.analogCircuitSolver.solve(
            this.circuitNodes,
            this.netlist,
            preRunDrivers,
            this.powerState,
          );

        this.arduino.getState().analogPinVoltages = {};
        this.arduino.getState().analogPinValues = {};

        for (const [pin, voltage] of this.analogState.pinVoltages) {
          const value =
            this.analogState.pinValues.get(pin) ?? 0;

          this.arduino.setAnalogInput(
            pin,
            voltage,
            value,
          );
        }

        if (this.firmwareLoaded) {
          const externalAnalogInputs: Record<string, number> = {};

          for (const [pin, voltage] of this.analogState.pinVoltages) {
            externalAnalogInputs[pin] = voltage;
          }

          this.avr.setExternalAnalogInputs(
            externalAnalogInputs,
          );
        }

        const sensorDigitalOutputs =
          new Map<string, 0 | 1>(
            this.analogState.digitalOutputs,
          );

        for (const [netId, level] of this.resolvePirOutputs()) {
          sensorDigitalOutputs.set(netId, level);
        }

        for (
          const [netId, level]
          of this.resolveDs1307SqwOutputs(
            this.simulatedCycles,
          )
        ) {
          sensorDigitalOutputs.set(netId, level);
        }

        this.arduino.getState().sensorDigitalOutputs =
          Object.fromEntries(
            sensorDigitalOutputs.entries(),
          );

        this.digitalInputState =
          this.digitalInputSolver.solve(
            this.circuitNodes,
            this.netlist,
            preRunDrivers,
            this.powerState,
            this.arduino.getDigitalInputModes(),
            sensorDigitalOutputs,
          );

        /*
         * Sensor outputs are active circuit sources. Keep their resolved
         * level authoritative at the Arduino input boundary as well.
         * This is especially important for PIR OUT: INPUT_PULLUP or other
         * board-side defaults must never mask the physical sensor level.
         */
        for (const [netId, level] of sensorDigitalOutputs) {
          for (const pin of this.netlist.netToPins.get(netId) ?? []) {
            if (!/^(?:D|A)\d+$/i.test(pin.pinId)) {
              continue;
            }

            const node = this.circuitNodes.find(
              (candidate) => candidate.id === pin.nodeId,
            );

            if (!node) {
              continue;
            }

            const type = String(
              node.data?.componentType ?? node.type ?? "",
            ).toLowerCase();

            if (
              type !== "arduino-uno" &&
              type !== "arduino"
            ) {
              continue;
            }

            const channel = Number(pin.pinId.slice(1));
            const pinNumber = /^A/i.test(pin.pinId)
              ? 14 + channel
              : channel;

            this.digitalInputState.pinLevels.set(
              createPinKeyForSimulation(node.id, pin.pinId),
              level,
            );

            this.arduino.setInputLevel(
              pinNumber,
              level,
            );
          }
        }

        for (const [
          pinKey,
          level,
        ] of this.digitalInputState.pinLevels) {
          const separator =
            pinKey.lastIndexOf(":");

          if (separator < 0) {
            continue;
          }

          const nodeId =
            pinKey.slice(0, separator);

          const pinId =
            pinKey.slice(separator + 1);

          if (!/^(?:D|A)\d+$/i.test(pinId)) {
            continue;
          }

          const channel = Number(pinId.slice(1));
          const pinNumber =
            /^A/i.test(pinId)
              ? 14 + channel
              : channel;

          const node =
            this.circuitNodes.find(
              (candidate) =>
                candidate.id === nodeId,
            );

          if (!node) {
            continue;
          }

          this.arduino.setInputLevel(
            pinNumber,
            level,
          );
        }

        if (this.firmwareLoaded) {
          const externalLevels: Record<
            string,
            0 | 1
          > = {};

          for (const [
            pinKey,
            level,
          ] of this.digitalInputState.pinLevels) {
            const separator =
              pinKey.lastIndexOf(":");

            if (separator < 0) {
              continue;
            }

            externalLevels[
              pinKey.slice(
                separator + 1,
              )
            ] = level;
          }

          this.avr.setExternalDigitalInputs(
            externalLevels,
          );

          this.avr.runCycles(
            this.cyclesPerFrame,
            (change) =>
              this.handleGpioChange(change.pin, change.level, change.cycle),
          );
        }
      }

      const digitalDrivers =
        this.arduino.getDigitalDrivers();

      this.digitalState =
        this.digitalSolver.solve(
          this.circuitNodes,
          this.circuitEdges,
          digitalDrivers,
        );

      if (this.netlist) {
        this.powerState =
          this.powerRailSolver.solve(
            this.netlist,
            this.arduino.getPowerDrivers(),
            digitalDrivers,
            this.circuitNodes,
          );

        for (const driver of this.arduino.getPowerDrivers()) {
          const voltage =
            this.powerState.pinVoltages[
              driver.pin
            ];

          if (typeof voltage === "number") {
            this.arduino.getState().pinVoltages[
              driver.pin
            ] = {
              pin: driver.pin,
              voltage,
              rail: driver.rail,
            };
          }
        }

        this.currentFlowState =
          this.currentFlowSolver.solve(
            this.circuitNodes,
            this.netlist,
            digitalDrivers,
            this.powerState,
          );

        this.arduino.getState().wireStates =
          this.currentFlowState.wireStates;
      }

      this.applyLedStates();
      this.applySevenSegmentStates();
      this.applyLcdStates();
      this.applySsd1306States();
      this.flushNeoPixelLatches(
        this.simulatedCycles,
      );
      this.applyNeoPixelStates();
      this.applyBuzzerStates();
      this.applyUltrasonicStates();
      this.refreshDiagnostics();

      this.emit();
    } catch (error) {
      this.clock.stop();

      const err =
        error instanceof Error
          ? error
          : new Error(String(error));

      this.setStatus("error");
      this.options.onError?.(err);
    }
  }

  private refreshDiagnostics(): void {
    const diagnostics: SimulationDiagnostics = {
      simulatedCycles: this.simulatedCycles,
      simulatedMs: (this.simulatedCycles / (this.options.config?.frequency ?? 16_000_000)) * 1000,
      frameCount: this.frameCount,
      pins: [],
      nets: [],
      components: [],
      faults: [],
      trace: this.activeTrace,
    };

    const netlist = this.netlist;
    if (!netlist) {
      this.arduino.getState().diagnostics = diagnostics;
      return;
    }

    for (const [netId, pins] of netlist.netToPins) {
      const active = this.currentFlowState.activeNets.has(netId);
      const currents = Array.from(netlist.wireToNet.entries())
        .filter(([, id]) => id === netId)
        .map(([wireId]) => this.currentFlowState.wireStates[wireId]?.currentMa)
        .filter((value): value is number => typeof value === "number");
      diagnostics.nets.push({
        netId,
        voltage: this.powerState.netVoltages[netId],
        currentMa: currents.length ? Math.max(...currents) : undefined,
        active,
        pins: pins.map((pin) => `${pin.nodeId}:${pin.pinId}`),
      });
    }

    for (const [pin, runtime] of Object.entries(this.arduino.getState().digitalPins)) {
      diagnostics.pins.push({
        pin: `D${Number(pin)}`,
        digitalLevel: runtime.level,
        mode: runtime.mode,
        voltage: runtime.mode === "output" ? runtime.level * 5 : undefined,
      });
    }

    for (const [pin, voltage] of Object.entries(this.arduino.getState().analogPinVoltages)) {
      diagnostics.pins.push({ pin, voltage });
    }

    for (const driver of this.arduino.getPowerDrivers()) {
      diagnostics.pins.push({ pin: driver.pin, voltage: driver.voltage });
    }

    const nodeById = new Map(this.circuitNodes.map((node) => [node.id, node]));
    for (const component of netlist.components) {
      const node = nodeById.get(component.id);
      if (!node) continue;
      const type = String(node.data?.componentType ?? node.type ?? "unknown").toLowerCase();
      const active =
        this.currentFlowState.activeComponents.has(component.id) ||
        (type === "buzzer" &&
          this.arduino.getState().buzzerStates[component.id]?.active === true) ||
        ((type === "hc-sr04" || type === "ultrasonic") &&
          (
            this.arduino.getState().ultrasonicStates[component.id]?.echoHigh === true ||
            this.arduino.getState().ultrasonicStates[component.id]?.triggerActive === true
          ));
      const currentMa = this.currentFlowState.componentCurrentMa[component.id] ??
        this.arduino.getState().buzzerStates[component.id]?.currentMa;
      const voltageDrop = this.currentFlowState.componentVoltageDrop[component.id] ?? (type.includes("led") && active ? 2 : undefined);
      diagnostics.components.push({
        id: component.id, type, voltageDrop, currentMa,
        powerMw: currentMa !== undefined && voltageDrop !== undefined ? currentMa * voltageDrop : undefined,
        active,
      });
    }

    diagnostics.faults = Array.from(new Set([
      ...this.powerState.conflicts,
      ...this.currentFlowState.conflicts,
      ...this.digitalState.conflicts,
      ...this.digitalInputState.conflicts,
      ...this.analogState.conflicts,
    ]));

    this.arduino.getState().diagnostics = diagnostics;
  }

  /** Execute exactly one simulation frame without starting the animation clock. */
  step(): void {
    if (this.clock.isRunning()) return;
    if (!this.netlist) throw new Error("Circuit topology has not been built.");
    this.tick();
  }

  getDiagnostics(): SimulationDiagnostics {
    return this.arduino.getState().diagnostics;
  }
  /**
   * Re-resolve matrix-keypad inputs immediately after firmware changes a
   * GPIO output during the real AVR scan loop.
   *
   * Keypad scanning is time-sensitive: Keypad.h drives one column LOW,
   * reads the rows, then moves to the next column. A once-per-frame input
   * snapshot is therefore not sufficient because the column can change
   * several times inside a single avrInstruction() run.
   *
   * Keep the Wokwi membrane-keypad as the UI/physical contact source and
   * let DigitalInputSolver resolve the actual row/column electrical path.
   * No keypad shortcut is injected into digitalRead().
   */
  private refreshMatrixKeypadInputs(): void {
    if (!this.netlist) {
      return;
    }

    const hasKeypad = this.circuitNodes.some((node) => {
      const type = String(
        node.data?.componentType ?? node.type ?? "",
      ).toLowerCase();

      return (
        type === "membrane-keypad" ||
        type === "keypad" ||
        type === "4x4-keypad"
      );
    });

    if (!hasKeypad) {
      return;
    }

    const sensorDigitalOutputs = new Map<string, 0 | 1>(
      Object.entries(
        this.arduino.getState().sensorDigitalOutputs ?? {},
      ) as Array<[string, 0 | 1]>,
    );

    /*
     * First resolve the normal circuit graph. This keeps keypad wiring
     * electrically connected to the rest of the circuit and preserves
     * the existing behavior for every non-keypad input.
     */
    const state = this.digitalInputSolver.solve(
      this.circuitNodes,
      this.netlist,
      this.arduino.getDigitalDrivers(),
      this.powerState,
      this.arduino.getDigitalInputModes(),
      sensorDigitalOutputs,
    );

    /*
     * A matrix keypad is scanned in time:
     *
     *   C1 LOW -> read R1..R4
     *   C2 LOW -> read R1..R4
     *   C3 LOW -> read R1..R4
     *   C4 LOW -> read R1..R4
     *
     * Therefore a once-per-frame graph result can be stale while the
     * firmware is inside Keypad::getKey(). Re-resolve only the keypad
     * contacts against the AVR's CURRENT GPIO output state.
     *
     * This models the real passive switch matrix instead of returning a
     * JavaScript key value from digitalRead().
     */
    const drivers = this.arduino.getDigitalDrivers();
    const driverLevels = new Map<string, 0 | 1>(
      drivers.map((driver) => [
        driver.pin.toUpperCase(),
        driver.level,
      ]),
    );

    const inputModes = this.arduino.getDigitalInputModes();

    const keypadNodes = this.circuitNodes.filter((node) => {
      const type = String(
        node.data?.componentType ?? node.type ?? "",
      ).toLowerCase();

      return (
        type === "membrane-keypad" ||
        type === "keypad" ||
        type === "4x4-keypad"
      );
    });

    for (const keypad of keypadNodes) {
      const component = this.netlist.components.find(
        (candidate) => candidate.id === keypad.id,
      );

      if (!component) {
        continue;
      }

      const pressedContacts = getKeypadContacts(keypad.id);

      for (const contact of pressedContacts) {
        const rowTerminal =
          component.terminals["R" + String(contact.row + 1)];

        const columnTerminal =
          component.terminals["C" + String(contact.column + 1)];

        if (!rowTerminal || !columnTerminal) {
          continue;
        }

        const rowPins =
          this.netlist.netToPins.get(rowTerminal) ?? [];

        const columnPins =
          this.netlist.netToPins.get(columnTerminal) ?? [];

        /*
         * The pressed membrane switch connects the whole row net to
         * the whole column net. If the currently driven column is LOW,
         * the row is physically pulled LOW. If it is HIGH, INPUT_PULLUP
         * keeps the row HIGH.
         */
        let columnIsLow = false;
        let columnHasOutput = false;

        for (const pin of columnPins) {
          const pinId = pin.pinId.toUpperCase();

          if (!/^(?:D|A)\d+$/.test(pinId)) {
            continue;
          }

          const mode = inputModes.get(pinId) ?? "input";

          if (mode !== "output") {
            continue;
          }

          const level = driverLevels.get(pinId);

          if (level === undefined) {
            continue;
          }

          columnHasOutput = true;

          if (level === 0) {
            columnIsLow = true;
            break;
          }
        }

        if (!columnHasOutput || !columnIsLow) {
          continue;
        }

        for (const pin of rowPins) {
          const pinId = pin.pinId.toUpperCase();

          if (!/^(?:D|A)\d+$/.test(pinId)) {
            continue;
          }

          const mode = inputModes.get(pinId) ?? "input";

          if (
            mode !== "input" &&
            mode !== "input_pullup"
          ) {
            continue;
          }

          const node = this.circuitNodes.find(
            (candidate) =>
              candidate.id === pin.nodeId,
          );

          if (!node) {
            continue;
          }

          const type = String(
            node.data?.componentType ?? node.type ?? "",
          ).toLowerCase();

          if (
            type !== "arduino-uno" &&
            type !== "arduino"
          ) {
            continue;
          }

          const channel = Number(pinId.slice(1));
          const pinNumber = /^A/i.test(pinId)
            ? 14 + channel
            : channel;

          state.pinLevels.set(
            createPinKeyForSimulation(
              node.id,
              pinId,
            ),
            0,
          );

          this.arduino.setInputLevel(
            pinNumber,
            0,
          );
        }
      }
    }

    this.digitalInputState = state;

    const externalLevels: Record<string, 0 | 1> = {};

    for (const [pinKey, inputLevel] of state.pinLevels) {
      const separator = pinKey.lastIndexOf(":");

      if (separator < 0) {
        continue;
      }

      const pinId = pinKey.slice(separator + 1);

      if (!/^(?:D|A)\d+$/i.test(pinId)) {
        continue;
      }

      externalLevels[pinId.toUpperCase()] = inputLevel;
    }

    this.avr.setExternalDigitalInputs(externalLevels);
  }

  private handleGpioChange(
    pin: string,
    level: 0 | 1,
    cycle: number,
  ): void {
    if (!this.netlist) {
      return;
    }

    // A matrix keypad is scanned inside the AVR instruction stream. Make
    // the just-written PORT/DDR state visible to the electrical solver
    // before resolving the keypad row inputs.
    this.avr.syncGpioToRuntime();
    this.refreshMatrixKeypadInputs();

    /*
     * Keep the firmware-generated GPIO state synchronized with the
     * physical parallel LCD bus. The LCD is sampled on E's falling edge.
     */
    this.parallelLcdGpioLevels.set(
      pin.toUpperCase(),
      level,
    );

    this.processSsd1306ResetGpioChange(pin, level);
    this.ssd1306SoftwareSpi?.handleGpioChange(
      pin,
      level,
    );
    this.processNeoPixelGpioChange(
      pin,
      level,
      cycle,
    );

    /*
     * LCD parallel bus transactions are latched on E's falling edge.
     * The AVR runner calls this from the real PORT register transitions,
     * so the LCD observes firmware-generated bus timing rather than
     * receiving text directly from the React UI.
     */
    this.processParallelLcdGpioChange(pin);
    this.processServoGpioChange(pin, level, cycle);

    for (const component of this.netlist.components) {
      const node =
        this.circuitNodes.find(
          (candidate) => candidate.id === component.id,
        );

      if (!node) {
        continue;
      }

      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (type !== "hc-sr04" && type !== "ultrasonic") {
        continue;
      }

      const trigNet =
        component.terminals.TRIG ??
        component.terminals.trig;

      if (!trigNet) {
        continue;
      }

      const trigPins =
        this.netlist.netToPins.get(trigNet) ?? [];

      const isConnectedToPin =
        trigPins.some(
          (ref) =>
            ref.pinId.toUpperCase() ===
            pin.toUpperCase(),
        );

      if (!isConnectedToPin) {
        continue;
      }

      const previous =
        this.ultrasonicTriggerLevels.get(node.id) ?? 0;

      this.ultrasonicTriggerLevels.set(
        node.id,
        level,
      );

      /*
       * HC-SR04 starts a measurement after a HIGH trigger pulse.
       * Arduino code normally drives TRIG HIGH for >=10us then LOW.
       * We schedule the ECHO pulse on the falling edge, after a small
       * acoustic/processing delay. The pulse width follows the real
       * HC-SR04 relation: distance(cm) = echo_us / 58.
       */
      if (previous === 1 && level === 0) {
        const props =
          node.data?.props &&
          typeof node.data.props === "object"
            ? (node.data.props as Record<string, unknown>)
            : {};

        const rawDistance =
          node.data?.ultrasonicDistanceCm ??
          props.distance ??
          100;

        const distanceCm = Math.max(
          2,
          Math.min(
            400,
            Number(rawDistance) || 100,
          ),
        );

        const echoDelayUs = 100;
        const echoPulseUs = distanceCm * 58;
        const echoStartCycle =
          cycle +
          Math.round(echoDelayUs * 16);

        const echoDurationCycles =
          Math.max(
            1,
            Math.round(echoPulseUs * 16),
          );

        const echoNet =
          component.terminals.ECHO ??
          component.terminals.echo;

        if (!echoNet) {
          continue;
        }

        const echoPins =
          this.netlist.netToPins.get(echoNet) ?? [];

        for (const echoPin of echoPins) {
          if (!/^(?:D|A)\d+$/i.test(echoPin.pinId)) {
            continue;
          }

          this.avr.scheduleDigitalPulse(
            echoPin.pinId.toUpperCase(),
            echoStartCycle,
            echoDurationCycles,
          );
        }
      }
    }
  }

  /**
   * Decode the real RC-servo control pulse generated by Arduino firmware.
   * Servo.h normally schedules ~50 Hz pulses with 544..2400 us high time.
   */
  private processServoGpioChange(
    pin: string,
    level: 0 | 1,
    cycle: number,
  ): void {
    if (!this.netlist) return;

    const normalizedPin = pin.toUpperCase();

    for (const component of this.netlist.components) {
      if (component.type !== "servo") continue;

      const signalNet = component.terminals.PWM;
      if (!signalNet) continue;

      const signalPins = this.netlist.netToPins.get(signalNet) ?? [];
      if (!signalPins.some((ref) => ref.pinId.toUpperCase() === normalizedPin)) {
        continue;
      }

      if (level === 1) {
        this.servoPulseStarts.set(component.id, cycle);
        continue;
      }

      const start = this.servoPulseStarts.get(component.id);
      if (start === undefined || cycle <= start) {
        continue;
      }

      const pulseWidthUs =
        ((cycle - start) / this.getServoClockFrequencyHz()) *
        1_000_000;

      /*
       * Ignore unrelated LOW transitions. A valid RC-servo pulse is
       * normally 544..2400 us; the wider window also accepts common
       * calibrated servos without allowing a frame/gap to become a
       * position command.
       */
      if (pulseWidthUs < 400 || pulseWidthUs > 3000) {
        this.servoPulseStarts.delete(component.id);
        continue;
      }

      const angle = Math.max(
        0,
        Math.min(
          180,
          ((pulseWidthUs - 544) / (2400 - 544)) * 180,
        ),
      );

      const powered = this.isServoPowered(component);

      this.arduino.getState().servoStates[component.id] = {
        id: component.id,
        angle: powered ? angle : 0,
        pulseWidthUs,
        signalPin: normalizedPin,
        powered,
      };

      this.servoPulseStarts.delete(component.id);
    }
  }

  private applySsd1306States(): void {
    const runtimeState =
      this.arduino.getState().ssd1306States;

    for (const [id, runtime] of this.ssd1306Runtimes) {
      runtimeState[id] = runtime.getState();
    }
  }

  private flushNeoPixelLatches(
    cycle: number,
  ): void {
    for (const runtime of this.neoPixelRuntimes.values()) {
      runtime.flush(cycle);

      const frame =
        runtime.consumeLatchedBits();

      if (frame) {
        this.distributeNeoPixelFrame(
          runtime.getState().id,
          frame,
        );
      }
    }
  }

  private applyNeoPixelStates(): void {
    const runtimeState =
      this.arduino.getState().neopixelStates;

    for (const [id, runtime] of this.neoPixelRuntimes) {
      runtimeState[id] = runtime.getState();
    }
  }

  private applyLcdStates(): void {
    const runtimeState =
      this.arduino.getState().lcdStates;

    for (const [id, runtime] of this.lcdRuntimes) {
      runtimeState[id] = runtime.getState();
    }
  }

  private processSsd1306ResetGpioChange(
    pin: string,
    level: 0 | 1,
  ): void {
    for (const display of this.ssd1306Runtimes.values()) {
      const resetPin =
        this.getConnectedArduinoGpioPin(
          display.id,
          "RST",
        );

      if (
        resetPin &&
        resetPin.toUpperCase() ===
          pin.toUpperCase()
      ) {
        display.setReset(level);
      }
    }
  }

  private processParallelLcdGpioChange(
    pin: string,
  ): void {
    if (!this.netlist) {
      return;
    }

    for (const component of this.netlist.components) {
      const runtime =
        this.lcdRuntimes.get(component.id);

      if (
        !runtime ||
        runtime.getState().mode === "i2c" ||
        !this.isLcdPowered(component)
      ) {
        continue;
      }

      const enableNet = component.terminals.E;
      if (!enableNet) {
        continue;
      }

      const enablePins =
        this.netlist.netToPins.get(enableNet) ?? [];

      const isEnablePin =
        enablePins.some(
          (ref) =>
            ref.pinId.toUpperCase() ===
            pin.toUpperCase(),
        );

      if (!isEnablePin) {
        continue;
      }

      const resolveDigitalPin = (
        netId: string | null | undefined,
      ): string | null => {
        if (!netId) {
          return null;
        }

        const pins =
          this.netlist!.netToPins.get(netId) ?? [];

        const ref =
          pins.find((candidate) =>
            /^(?:D|A)\d+$/i.test(candidate.pinId),
          );

        return ref?.pinId.toUpperCase() ?? null;
      };

      const rsPin =
        resolveDigitalPin(component.terminals.RS);
      const rwPin =
        resolveDigitalPin(component.terminals.RW);
      const ePin =
        resolveDigitalPin(component.terminals.E);

      if (!ePin) {
        continue;
      }

      const dataPins = ["D0","D1","D2","D3","D4","D5","D6","D7"]
        .map((name) => ({
          name,
          pin: resolveDigitalPin(
            component.terminals[name],
          ),
        }));

      const readLevel = (gpioPin: string | null): 0 | 1 =>
        gpioPin
          ? (
              this.parallelLcdGpioLevels.get(
                gpioPin.toUpperCase(),
              ) ??
              this.avr.getGpioLevel(gpioPin)
            )
          : 0;

      const levels = dataPins.reduce(
        (value, item, index) =>
          value |
          (readLevel(item.pin) << index),
        0,
      );

      const mode = runtime.getState().mode;
      const data =
        mode === "8bit"
          ? levels
          : (
              (levels >> 4) & 0x0f
            );

      runtime.processParallelEdge({
        rs: readLevel(rsPin),
        rw: readLevel(rwPin),
        enable: readLevel(ePin),
        data,
      });
    }
  }

  private updateNeoPixelPowerStates(): void {
    if (!this.netlist) {
      return;
    }

    for (const component of this.netlist.components) {
      const runtime =
        this.neoPixelRuntimes.get(component.id);

      if (!runtime) {
        continue;
      }

      const vdd =
        component.terminals.VDD ??
        component.terminals.VCC;
      const gnd =
        component.terminals.VSS ??
        component.terminals.GND;

      const powered =
        typeof vdd === "string" &&
        typeof gnd === "string" &&
        (
          this.powerState.sourceNets.has(vdd) ||
          (this.powerState.netVoltages[vdd] ?? 0) >= 4.0
        ) &&
        (
          this.powerState.groundNets.has(gnd) ||
          Math.abs(
            this.powerState.netVoltages[gnd] ?? 999,
          ) < 0.05
        );

      runtime.setPowered(powered);
    }
  }

  private processNeoPixelGpioChange(
    pin: string,
    level: 0 | 1,
    cycle: number,
  ): void {
    if (!this.netlist) {
      return;
    }

    for (const runtime of this.neoPixelRuntimes.values()) {
      const dataPin =
        this.getConnectedArduinoGpioPin(
          runtime.getState().id,
          "DIN",
        );

      if (
        dataPin &&
        dataPin.toUpperCase() ===
          pin.toUpperCase()
      ) {
        runtime.handleGpioChange(
          level,
          cycle,
        );

        const frame =
          runtime.consumeLatchedBits();

        if (frame) {
          this.distributeNeoPixelFrame(
            runtime.getState().id,
            frame,
          );
        }
      }
    }
  }

  private distributeNeoPixelFrame(
    rootId: string,
    frame: number[],
  ): void {
    if (!this.netlist) {
      return;
    }

    const chain: string[] = [];
    const visited = new Set<string>();
    let currentId: string | null = rootId;

    while (currentId && !visited.has(currentId)) {
      visited.add(currentId);
      chain.push(currentId);

      const current =
        this.netlist.components.find(
          (component) =>
            component.id === currentId,
        );

      const dout =
        current?.terminals.DOUT ??
        current?.terminals.DO;

      if (!dout) {
        break;
      }

      const next =
        this.netlist.components.find(
          (component) =>
            this.neoPixelRuntimes.has(component.id) &&
            component.id !== currentId &&
            (
              component.terminals.DIN === dout ||
              component.terminals.DI === dout
            ),
        );

      currentId = next?.id ?? null;
    }

    for (
      let index = 0;
      index < chain.length;
      index += 1
    ) {
      const pixel =
        this.neoPixelRuntimes.get(
          chain[index],
        );

      if (!pixel) {
        continue;
      }

      const start = index * 24;
      pixel.applyFrameBits(
        frame.slice(start, start + 24),
      );
    }
  }

  private applySevenSegmentStates(): void {
    if (!this.netlist) {
      return;
    }

    const runtimeState =
      this.arduino.getState().sevenSegmentStates;

    const segmentNames = [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "DP",
    ];

    const drivers =
      this.arduino.getDigitalDrivers();

    const netHasDriverLevel = (
      netId: string,
      level: 0 | 1,
      visited = new Set<string>(),
    ): boolean => {
      if (visited.has(netId)) {
        return false;
      }

      visited.add(netId);

      const pins =
        this.netlist!.netToPins.get(netId) ?? [];

      if (
        pins.some((pin) =>
          drivers.some((driver) =>
            driver.pin.toUpperCase() ===
              pin.pinId.toUpperCase() &&
            (
              driver.level === level ||
              (
                level === 1 &&
                (driver.pwmDuty ?? 0) > 0
              )
            ),
          ),
        )
      ) {
        return true;
      }

      /*
       * Segment pins are commonly connected through a current
       * limiting resistor. Follow resistor-only links so the
       * display state is derived from the real circuit topology.
       */
      for (const resistor of this.netlist!.components) {
        if (resistor.type !== "resistor") {
          continue;
        }

        const pin1 =
          resistor.terminals.pin1;
        const pin2 =
          resistor.terminals.pin2;

        if (
          pin1 === netId &&
          pin2 &&
          netHasDriverLevel(
            pin2,
            level,
            new Set(visited),
          )
        ) {
          return true;
        }

        if (
          pin2 === netId &&
          pin1 &&
          netHasDriverLevel(
            pin1,
            level,
            new Set(visited),
          )
        ) {
          return true;
        }
      }

      return false;
    };

    for (const component of this.netlist.components) {
      const node =
        this.circuitNodes.find(
          (candidate) =>
            candidate.id === component.id,
        );

      if (!node) {
        continue;
      }

      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (
        type !== "7segment" &&
        type !== "sevensegment" &&
        type !== "seven-segment"
      ) {
        continue;
      }

      const props =
        node.data?.props &&
        typeof node.data.props === "object"
          ? (node.data.props as Record<string, unknown>)
          : {};

      const configuredCommon =
        String(
          props.common ??
            node.data?.common ??
            "anode",
        ).toLowerCase() === "cathode"
          ? "cathode"
          : "anode";

      const parsedDigits =
        Number(
          props.digits ??
            node.data?.digits ??
            1,
        );

      const digits =
        [1, 2, 3, 4].includes(
          parsedDigits,
        )
          ? parsedDigits
          : 1;

      const values: number[] = [];
      let colon = false;

      for (
        let digitIndex = 0;
        digitIndex < digits;
        digitIndex += 1
      ) {
        const commonPin =
          digits === 1
            ? (
                component.terminals["COM.1"]
                  ? "COM.1"
                  : component.terminals["COM1"]
                    ? "COM1"
                    : component.terminals["COM.2"]
                      ? "COM.2"
                      : component.terminals["COM2"]
                        ? "COM2"
                        : "COM"
              )
            : "DIG" +
              (digitIndex + 1);

        const commonNet =
          component.terminals[commonPin];

        const common =
          this.powerState.groundNets.has(commonNet as string)
            ? "cathode"
            : this.powerState.sourceNets.has(commonNet as string)
              ? "anode"
              : configuredCommon;

        const commonEnabled =
          typeof commonNet === "string" &&
          (
            common === "cathode"
              ? (
                  this.powerState.groundNets.has(commonNet) ||
                  netHasDriverLevel(commonNet, 0)
                )
              : (
                  this.powerState.sourceNets.has(commonNet) ||
                  netHasDriverLevel(commonNet, 1)
                )
          );

        for (const segmentName of segmentNames) {
          const segmentNet =
            component.terminals[
              segmentName
            ];

          const lit =
            commonEnabled &&
            typeof segmentNet === "string" &&
            (
              this.currentFlowState.activeNets.has(
                segmentNet,
              ) ||
              (
                common === "cathode"
                  ? netHasDriverLevel(
                      segmentNet,
                      1,
                    )
                  : netHasDriverLevel(
                      segmentNet,
                      0,
                    )
              )
            );

          values.push(lit ? 1 : 0);
        }

        if (digitIndex === 0) {
          const colonNet =
            component.terminals.CLN;

          colon =
            commonEnabled &&
            typeof colonNet === "string" &&
            this.currentFlowState.activeNets.has(
              colonNet,
            );
        }

        runtimeState[node.id] = {
        id: node.id,
        digits,
        common,
        values,
        colon,
      };
      }

      
    }
  }

  private applyBuzzerStates(): void {
    if (!this.netlist) {
      return;
    }

    const runtimeState =
      this.arduino.getState().buzzerStates;

    for (const component of this.netlist.components) {
      const node =
        this.circuitNodes.find(
          (candidate) => candidate.id === component.id,
        );

      if (!node) {
        continue;
      }

      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (type !== "buzzer") {
        continue;
      }

      const positive =
        component.terminals.positive ??
        component.terminals["2"];

      const negative =
        component.terminals.negative ??
        component.terminals["1"];

      const connectedPins = new Set<string>();

      for (const netId of [positive, negative]) {
        if (!netId) continue;

        for (const pin of this.netlist.netToPins.get(netId) ?? []) {
          if (/^(?:D|A)\d+$/i.test(pin.pinId)) {
            connectedPins.add(pin.pinId.toUpperCase());
          }
        }
      }

      let frequencyHz: number | undefined;

      for (const pin of connectedPins) {
        const measured =
          this.avr.getToggleFrequencyHz(
            pin,
            this.cyclesPerFrame,
          );

        if (
          measured !== undefined &&
          measured >= 20 &&
          (
            frequencyHz === undefined ||
            measured > frequencyHz
          )
        ) {
          frequencyHz = measured;
        }
      }

      const electricalCurrent =
        this.currentFlowState.componentCurrentMa[node.id];

      const active =
        this.currentFlowState.activeComponents.has(node.id) ||
        frequencyHz !== undefined;

      runtimeState[node.id] = {
        id: node.id,
        active,
        currentMa: electricalCurrent,
        frequencyHz,
      };
    }
  }

  private applyUltrasonicStates(): void {
    if (!this.netlist) {
      return;
    }

    const runtimeState =
      this.arduino.getState().ultrasonicStates;

    for (const component of this.netlist.components) {
      const node =
        this.circuitNodes.find(
          (candidate) => candidate.id === component.id,
        );

      if (!node) continue;

      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (type !== "hc-sr04" && type !== "ultrasonic") {
        continue;
      }

      const props =
        node.data?.props &&
        typeof node.data.props === "object"
          ? (node.data.props as Record<string, unknown>)
          : {};

      const distanceCm = Math.max(
        2,
        Math.min(
          400,
          Number(
            node.data?.ultrasonicDistanceCm ??
              props.distance ??
              100,
          ) || 100,
        ),
      );

      const echoNet =
        component.terminals.ECHO ??
        component.terminals.echo;

      const echoHigh =
        echoNet
          ? Array.from(
              this.netlist.netToPins.get(echoNet) ?? [],
            ).some((pin) =>
              this.arduino.digitalRead(
                this.pinToRuntimeNumber(pin.pinId),
              ) === 1,
            )
          : false;

      const trigNet =
        component.terminals.TRIG ??
        component.terminals.trig;

      const triggerActive =
        trigNet
          ? Array.from(
              this.netlist.netToPins.get(trigNet) ?? [],
            ).some((pin) =>
              this.arduino.digitalRead(
                this.pinToRuntimeNumber(pin.pinId),
              ) === 1,
            )
          : false;

      runtimeState[node.id] = {
        id: node.id,
        distanceCm,
        echoHigh,
        triggerActive,
        echoPulseUs: distanceCm * 58,
      };
    }
  }

  private pinToRuntimeNumber(pin: string): number {
    if (/^A\d+$/i.test(pin)) {
      return 14 + Number(pin.slice(1));
    }

    if (/^D\d+$/i.test(pin)) {
      return Number(pin.slice(1));
    }

    return -1;
  }

  private applyLedStates(): void {
    for (const node of this.circuitNodes) {
      const type = String(
        node.data?.componentType ??
          node.type ??
          "",
      ).toLowerCase();

      if (!type.includes("led")) {
        continue;
      }

      const anode =
        this.digitalSolver.getPinLevel(
          this.digitalState,
          node.id,
          String(
            node.data?.anodePinId ??
              "anode",
          ),
        );

      const cathode =
        this.digitalSolver.getPinLevel(
          this.digitalState,
          node.id,
          String(
            node.data?.cathodePinId ??
              "cathode",
          ),
        );

      const firmwareDrivenOn =
        anode === 1 &&
        cathode === 0;

      const electricallyPoweredOn =
        this.currentFlowState.activeComponents.has(
          node.id,
        );

      const isOn =
        firmwareDrivenOn ||
        electricallyPoweredOn;

      const solvedBrightness =
        this.currentFlowState.componentBrightness[
          node.id
        ];

      const brightness =
        isOn
          ? (
              typeof solvedBrightness === "number"
                ? solvedBrightness
                : 1
            )
          : 0;

      this.arduino.getState().ledStates[
        node.id
      ] = {
        id: node.id,
        isOn,
        brightness,
        color:
          typeof node.data?.color ===
          "string"
            ? node.data.color
            : undefined,
      };

    }
  }

  pause(): void {
    this.clock.stop();
    this.setStatus("paused");
  }

  stop(): void {
    this.clock.stop();
    clearKeypadContacts();
    this.arduino.reset();
    this.ultrasonicTriggerLevels.clear();
    this.pirRuntime.clear();
    this.simulatedCycles = 0;
    this.frameCount = 0;

    this.analogState = {
      pinVoltages: new Map(),
      pinValues: new Map(),
      digitalOutputs: new Map(),
      sensorVoltages: new Map(),
      sensorResistanceOhms: new Map(),
      conflicts: [],
    };



    this.digitalState = {
      pinLevels: new Map(),
      conflicts: [],
    };

    this.currentFlowState = {
      wireStates: {},
      activeNets: new Set(),
      activeComponents: new Set(),
      componentBrightness: {},
      componentCurrentMa: {},
      componentVoltageDrop: {},
      conflicts: [],
    };

    this.digitalInputState = {
      pinLevels: new Map(),
      conflicts: [],
      floatingPins: [],
    };

    this.powerState = {
      netVoltages: {},
      pinVoltages: {},
      sourceNets: new Map(),
      groundNets: new Set(),
      conflicts: [],
    };

    this.setStatus("stopped");
  }

  reset(): void {
    this.clock.stop();
    clearKeypadContacts();
    this.arduino.reset();
    this.ultrasonicTriggerLevels.clear();
    this.pirRuntime.clear();
    this.simulatedCycles = 0;
    this.frameCount = 0;
    this.avr.reset();

    this.analogState = {
      pinVoltages: new Map(),
      pinValues: new Map(),
      digitalOutputs: new Map(),
      sensorVoltages: new Map(),
      sensorResistanceOhms: new Map(),
      conflicts: [],
    };



    this.digitalState = {
      pinLevels: new Map(),
      conflicts: [],
    };

    this.currentFlowState = {
      wireStates: {},
      activeNets: new Set(),
      activeComponents: new Set(),
      componentBrightness: {},
      componentCurrentMa: {},
      componentVoltageDrop: {},
      conflicts: [],
    };

    this.digitalInputState = {
      pinLevels: new Map(),
      conflicts: [],
      floatingPins: [],
    };

    this.powerState = {
      netVoltages: {},
      pinVoltages: {},
      sourceNets: new Map(),
      groundNets: new Set(),
      conflicts: [],
    };

    this.netlist = null;
    this.firmwareLoaded = false;
    this.activeTrace = undefined;

    this.setStatus("idle");
  }

  /**
   * Trace one electrical net through the live netlist.
   * Physical wires are nets; components are boundaries between nets.
   */
  traceNet(netId: string): SimulationTrace {
    const netlist = this.netlist;
    const diagnostics = this.arduino.getState().diagnostics;

    if (!netlist || !netlist.netToPins.has(netId)) {
      const trace: SimulationTrace = {
        target: netId,
        status: "blocked",
        summary: "Net was not found in the current circuit.",
        steps: [{ kind: "fault", id: "trace:not-found", label: "NET_NOT_FOUND" }],
        netIds: [],
        componentIds: [],
        faults: ["NET_NOT_FOUND:" + netId],
      };
      this.activeTrace = trace;
      diagnostics.trace = trace;
      this.emit();
      return trace;
    }

    const steps: SimulationTraceStep[] = [];
    const netIds: string[] = [];
    const componentIds: string[] = [];
    const visitedNets = new Set<string>();
    const visitedComponents = new Set<string>();
    const queue: string[] = [netId];
    let reachedSource = false;
    let reachedGround = false;

    const netById = new Map(diagnostics.nets.map((net) => [net.netId, net]));
    const componentById = new Map(diagnostics.components.map((component) => [component.id, component]));

    while (queue.length > 0 && steps.length < 80) {
      const currentNet = queue.shift()!;
      if (visitedNets.has(currentNet)) continue;
      visitedNets.add(currentNet);
      netIds.push(currentNet);

      const netMeasurement = netById.get(currentNet);
      steps.push({
        kind: "net",
        id: currentNet,
        label: currentNet,
        voltage: netMeasurement?.voltage,
        currentMa: netMeasurement?.currentMa,
        active: netMeasurement?.active,
      });

      if (this.powerState.groundNets.has(currentNet)) reachedGround = true;
      if (this.powerState.sourceNets.has(currentNet)) reachedSource = true;

      const pins = netlist.netToPins.get(currentNet) ?? [];
      for (const pin of pins) {
        steps.push({
          kind: "pin",
          id: pin.nodeId + ":" + pin.pinId,
          label: pin.nodeId + ":" + pin.pinId,
        });
      }

      for (const component of netlist.components) {
        const connectedTerminals = Object.entries(component.terminals)
          .filter(([, connectedNet]) => connectedNet === currentNet)
          .map(([terminal]) => terminal);

        if (connectedTerminals.length === 0) continue;

        if (!visitedComponents.has(component.id)) {
          visitedComponents.add(component.id);
          componentIds.push(component.id);
          const measurement = componentById.get(component.id);
          steps.push({
            kind: "component",
            id: component.id,
            label: component.type + " (" + connectedTerminals.join(", ") + ")",
            voltage: measurement?.voltageDrop,
            currentMa: measurement?.currentMa,
            active: measurement?.active,
          });
        }

        for (const otherNet of Object.values(component.terminals)) {
          if (!otherNet || otherNet === currentNet || visitedNets.has(otherNet)) continue;
          queue.push(otherNet);
        }
      }
    }

    const faults = diagnostics.faults.filter((fault) =>
      fault.includes(netId) || fault.startsWith("POWER_CONFLICT") || fault.startsWith("SHORT_CIRCUIT"),
    );

    const status: SimulationTrace["status"] =
      faults.length > 0
        ? "blocked"
        : reachedSource || reachedGround
          ? "complete"
          : "floating";

    const summary =
      status === "complete"
        ? reachedSource && reachedGround
          ? "Trace reaches a source and GND through the circuit."
          : reachedSource
            ? "Trace reaches an electrical source."
            : "Trace reaches GND."
        : status === "blocked"
          ? "Trace is affected by an electrical fault."
          : "Trace does not currently reach a known source or GND.";

    const trace: SimulationTrace = {
      target: netId,
      status,
      summary,
      steps,
      netIds,
      componentIds,
      faults,
    };

    this.activeTrace = trace;
    diagnostics.trace = trace;
    this.emit();
    return trace;
  }

  tracePin(nodeId: string, pinId: string): SimulationTrace {
    const netlist = this.netlist;
    if (!netlist) return this.traceNet("__missing__");

    const netId = netlist.pinToNet.get(nodeId + ":" + pinId);
    if (!netId) return this.traceNet("__missing__");
    return this.traceNet(netId);
  }

  traceComponent(componentId: string): SimulationTrace {
    const netlist = this.netlist;
    if (!netlist) return this.traceNet("__missing__");

    const component = netlist.components.find((item) => item.id === componentId);
    const netId = component
      ? Object.values(component.terminals).find((value): value is string => Boolean(value))
      : undefined;

    if (!netId) return this.traceNet("__missing__");
    return this.traceNet(netId);
  }

  clearTrace(): void {
    this.activeTrace = undefined;
    this.arduino.getState().diagnostics.trace = undefined;
    this.emit();
  }
  getArduino(): ArduinoUnoRuntime {
    return this.arduino;
  }

  getAvr(): Avr8jsRunner {
    return this.avr;
  }

  getNetlist(): Netlist | null {
    return this.netlist;
  }

  getDigitalState(): DigitalCircuitState {
    return this.digitalState;
  }

  getDigitalInputState(): DigitalInputState {
    return this.digitalInputState;
  }

  getCurrentFlowState(): CurrentFlowState {
    return this.currentFlowState;
  }

  getPowerState(): PowerRailState {
    return this.powerState;
  }

  getAnalogState(): AnalogInputState {
    return this.analogState;
  }

  getState(): ArduinoUnoRuntimeState {
    return this.arduino.getState();
  }
}
