import type { CircuitPin } from "../types/pin.types";

// =====================================================
// ESP32 DEVKIT V1 (30-PIN) PIN DEFINITIONS
// =====================================================

export const esp32Pins: CircuitPin[] = [
  // 1. Left Side Pins (EN to VIN)
  {
    id: "pin_en",
    label: "EN",
    alias: "Enable / Reset",
    type: "terminal",
    direction: "passive",
    description: "Enable / Reset pin. Pull LOW to reset ESP32.",
  },
  {
    id: "pin_vp",
    label: "VP",
    alias: "GPIO36 / VP",
    type: "terminal",
    direction: "passive",
    description: "GPIO36 / ADC1_CH0 / Input only pin.",
  },
  {
    id: "pin_vn",
    label: "VN",
    alias: "GPIO39 / VN",
    type: "terminal",
    direction: "passive",
    description: "GPIO39 / ADC1_CH3 / Input only pin.",
  },
  {
    id: "pin_34",
    label: "D34",
    alias: "GPIO34",
    type: "terminal",
    direction: "passive",
    description: "GPIO34 / ADC1_CH6 / Input only pin.",
  },
  {
    id: "pin_35",
    label: "D35",
    alias: "GPIO35",
    type: "terminal",
    direction: "passive",
    description: "GPIO35 / ADC1_CH7 / Input only pin.",
  },
  {
    id: "pin_32",
    label: "D32",
    alias: "GPIO32",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO32 / ADC1_CH4 / Touch9 / PWM.",
  },
  {
    id: "pin_33",
    label: "D33",
    alias: "GPIO33",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO33 / ADC1_CH5 / Touch8 / PWM.",
  },
  {
    id: "pin_25",
    label: "D25",
    alias: "GPIO25",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO25 / DAC1 / ADC2_CH8 / PWM.",
  },
  {
    id: "pin_26",
    label: "D26",
    alias: "GPIO26",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO26 / DAC2 / ADC2_CH9 / PWM.",
  },
  {
    id: "pin_27",
    label: "D27",
    alias: "GPIO27",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO27 / ADC2_CH7 / Touch7 / PWM.",
  },
  {
    id: "pin_14",
    label: "D14",
    alias: "GPIO14",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO14 / ADC2_CH6 / Touch6 / SPI SCK.",
  },
  {
    id: "pin_12",
    label: "D12",
    alias: "GPIO12",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO12 / ADC2_CH5 / Touch5 / SPI MISO.",
  },
  {
    id: "pin_13",
    label: "D13",
    alias: "GPIO13",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO13 / ADC2_CH4 / Touch4 / SPI MOSI.",
  },
  {
    id: "pin_gnd_1",
    label: "GND",
    alias: "Ground 1",
    type: "ground",
    direction: "passive",
    description: "Ground connection pin.",
  },
  {
    id: "pin_vin",
    label: "VIN",
    alias: "5V Input",
    type: "power",
    direction: "passive",
    description: "External 5V power input pin.",
  },

  // 2. Right Side Pins (3V3 to D23)
  {
    id: "pin_3v3",
    label: "3V3",
    alias: "3.3V Power Output",
    type: "power",
    direction: "passive",
    description: "Regulated 3.3V power output pin.",
  },
  {
    id: "pin_gnd_2",
    label: "GND",
    alias: "Ground 2",
    type: "ground",
    direction: "passive",
    description: "Ground connection pin.",
  },
  {
    id: "pin_15",
    label: "D15",
    alias: "GPIO15",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO15 / ADC2_CH3 / Touch3 / PWM.",
  },
  {
    id: "pin_2",
    label: "D2",
    alias: "GPIO2",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO2 / ADC2_CH2 / Touch2 / Built-in LED.",
  },
  {
    id: "pin_0",
    label: "D0",
    alias: "GPIO0",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO0 / ADC2_CH1 / Touch1 / Boot Button.",
  },
  {
    id: "pin_4",
    label: "D4",
    alias: "GPIO4",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO4 / ADC2_CH0 / Touch0 / PWM.",
  },
  {
    id: "pin_16",
    label: "RX2",
    alias: "GPIO16 / RX2",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO16 / UART2 RX.",
  },
  {
    id: "pin_17",
    label: "TX2",
    alias: "GPIO17 / TX2",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO17 / UART2 TX.",
  },
  {
    id: "pin_5",
    label: "D5",
    alias: "GPIO5",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO5 / VSPI SS.",
  },
  {
    id: "pin_18",
    label: "D18",
    alias: "GPIO18",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO18 / VSPI SCK.",
  },
  {
    id: "pin_19",
    label: "D19",
    alias: "GPIO19",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO19 / VSPI MISO.",
  },
  {
    id: "pin_21",
    label: "D21",
    alias: "GPIO21",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO21 / I2C SDA.",
  },
  {
    id: "pin_3",
    label: "RX0",
    alias: "GPIO3 / RX0",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO3 / UART0 RX.",
  },
  {
    id: "pin_1",
    label: "TX0",
    alias: "GPIO1 / TX0",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO1 / UART0 TX.",
  },
  {
    id: "pin_22",
    label: "D22",
    alias: "GPIO22",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO22 / I2C SCL.",
  },
  {
    id: "pin_23",
    label: "D23",
    alias: "GPIO23",
    type: "terminal",
    direction: "bidirectional",
    description: "GPIO23 / VSPI MOSI.",
  },
];

// =====================================================
// PIN LOOKUP
// =====================================================

export const esp32PinsById = Object.fromEntries(
  esp32Pins.map((pin) => [pin.id, pin])
) as Record<string, CircuitPin>;