import type { CircuitPin } from "../types/pin.types";

// =====================================================
// LCD 1602 I2C MODULE PIN DEFINITIONS
// =====================================================
//
// IMPORTANT
//
// CircuitPin.id is the canonical pin ID.
//
// React Flow Handle IDs must be exactly the same:
//
// GND → Handle gnd
// VCC → Handle vcc
// SDA → Handle sda
// SCL → Handle scl
//
// The I2C LCD 1602 module uses a 4-pin I2C communication 
// interface for power and data transmission.
//
// =====================================================

export const lcd1602I2cPins: CircuitPin[] = [
  // =====================================================
  // GND (GROUND)
  // =====================================================

  {
    id: "gnd",
    label: "GND",
    alias: "Ground (0V)",
    type: "terminal",
    direction: "passive",
    description:
      "Ground reference terminal. Connects to the ground (0V) of the power supply.",
  },

  // =====================================================
  // VCC (POWER)
  // =====================================================

  {
    id: "vcc",
    label: "VCC",
    alias: "Power (+5V)",
    type: "terminal",
    direction: "passive",
    description:
      "Power supply input terminal. Connects to positive voltage (typically +5V DC).",
  },

  // =====================================================
  // SDA (SERIAL DATA)
  // =====================================================

  {
    id: "sda",
    label: "SDA",
    alias: "Serial Data",
    type: "terminal",
    direction: "passive",
    description:
      "I2C Serial Data line. Used to transfer data bidirectionally between the microcontroller and the display.",
  },

  // =====================================================
  // SCL (SERIAL CLOCK)
  // =====================================================

  {
    id: "scl",
    label: "SCL",
    alias: "Serial Clock",
    type: "terminal",
    direction: "passive",
    description:
      "I2C Serial Clock line. Carries the timing clock signal generated by the microcontroller for synchronized data transfer.",
  },
];

// =====================================================
// PIN LOOKUP
// =====================================================

export const lcd1602I2cPinsById = Object.fromEntries(
  lcd1602I2cPins.map((pin) => [pin.id, pin])
) as Record<string, CircuitPin>;