import { analog, i2c, spi, usart } from './pin';

export const ARDUINO_UNO_PIN = [
    { name: 'A5.2', x: 87, y: 9, dir: "top", signals: [analog(5), i2c('SCL')] },
    { name: 'A4.2', x: 97, y: 9, dir: "top", signals: [analog(4), i2c('SDA')] },
    { name: 'AREF', x: 106, y: 9, dir: "top", signals: [] },
    { name: 'GND.1', x: 115.5, y: 9, dir: "top", signals: [{ type: 'power', signal: 'GND' }] },
    { name: '13', x: 125, y: 9, dir: "top", signals: [spi('SCK')] },
    { name: '12', x: 134.5, y: 9, dir: "top", signals: [spi('MISO')] },
    { name: '11', x: 144, y: 9, dir: "top", signals: [spi('MOSI'), { type: 'pwm' }] },
    { name: '10', x: 153.5, y: 9, dir: "top", signals: [spi('SS'), { type: 'pwm' }] },
    { name: '9', x: 163, y: 9, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '8', x: 173, y: 9, dir: "top", signals: [] },
    { name: '7', x: 189, y: 9, dir: "top", signals: [] },
    { name: '6', x: 198.5, y: 9, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '5', x: 208, y: 9, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '4', x: 217.5, y: 9, dir: "top", signals: [] },
    { name: '3', x: 227, y: 9, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '2', x: 236.5, y: 9, dir: "top", signals: [] },
    { name: '1', x: 246, y: 9, dir: "top", signals: [usart('TX')] },
    { name: '0', x: 255.5, y: 9, dir: "top", signals: [usart('RX')] },
    { name: 'IOREF', x: 131, y: 191.5, dir: "bottom",signals: [] },
    { name: 'RESET', x: 140.5, y: 191.5, dir: "bottom", signals: [] },
    { name: '3.3V', x: 150, y: 191.5, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 3.3 }] },
    { name: '5V', x: 160, y: 191.5, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 5 }] },
    { name: 'GND.2', x: 169.5, y: 191.5, dir: "bottom", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'GND.3', x: 179, y: 191.5, dir: "bottom", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'VIN', x: 188.5, y: 191.5, dir: "bottom", signals: [{ type: 'power', signal: 'VCC' }] },
    { name: 'A0', x: 208, y: 191.5, dir: "bottom", signals: [analog(0)] },
    { name: 'A1', x: 217.5, y: 191.5, dir: "bottom", signals: [analog(1)] },
    { name: 'A2', x: 227, y: 191.5, dir: "bottom", signals: [analog(2)] },
    { name: 'A3', x: 236.5, y: 191.5, dir: "bottom", signals: [analog(3)] },
    { name: 'A4', x: 246, y: 191.5, dir: "bottom", signals: [analog(4), i2c('SDA')] },
    { name: 'A5', x: 255.5, y: 191.5, dir: "bottom", signals: [analog(5), i2c('SCL')] },
  ]