import { analog, i2c, spi, usart } from './pin';

export const ARDUINO_NANO_PIN= 
  [
    { name: '12', x: 19.7, y: 4.8, dir: "top", signals: [spi('MISO')] },
    { name: '11', x: 29.3, y: 4.8, dir: "top", signals: [spi('MOSI'), { type: 'pwm' }] },
    { name: '10', x: 38.9, y: 4.8, dir: "top", signals: [spi('SS'), { type: 'pwm' }] },
    { name: '9', x: 48.5, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '8', x: 58.1, y: 4.8, dir: "top", signals: [] },
    { name: '7', x: 67.7, y: 4.8, dir: "top", signals: [] },
    { name: '6', x: 77.3, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '5', x: 86.9, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '4', x: 96.5, y: 4.8, dir: "top", signals: [] },
    { name: '3', x: 106.1, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: '2', x: 115.7, y: 4.8, dir: "top", signals: [] },
    { name: 'GND.2', x: 125.3, y: 4.8, dir: "top", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'RESET.2', x: 134.9, y: 4.8, dir: "top", signals: [] },
    { name: '0', x: 144.5, y: 4.8, dir: "top", signals: [usart('TX')] },
    { name: '1', x: 154.1, y: 4.8, dir: "top", signals: [usart('RX')] },
    { name: '13', x: 19.7, y: 62.4, dir: "bottom", signals: [spi('SCK')] },
    { name: '3.3V', x: 29.3, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 3.3 }] },
    { name: 'AREF', x: 38.9, y: 62.4, dir: "bottom", signals: [] },
    { name: 'A0', x: 48.5, y: 62.4, dir: "bottom", signals: [analog(0)] },
    { name: 'A1', x: 58.1, y: 62.4, dir: "bottom", signals: [analog(1)] },
    { name: 'A2', x: 67.7, y: 62.4, dir: "bottom", signals: [analog(2)] },
    { name: 'A3', x: 77.3, y: 62.4, dir: "bottom", signals: [analog(3)] },
    { name: 'A4', x: 86.9, y: 62.4, dir: "bottom", signals: [analog(4), i2c('SDA')] },
    { name: 'A5', x: 96.5, y: 62.4, dir: "bottom", signals: [analog(5), i2c('SCL')] },
    { name: 'A6', x: 106.1, y: 62.4, dir: "bottom", signals: [analog(6)] },
    { name: 'A7', x: 115.7, y: 62.4, dir: "bottom", signals: [analog(7)] },
    { name: '5V', x: 125.3, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 5 }] },
    { name: 'RESET', x: 134.9, y: 62.4, dir: "bottom", signals: [] },
    { name: 'GND.1', x: 144.5, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'VIN', x: 154.1, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC' }] },

    { name: '12.2', x: 163.7, y: 43.2, dir: "right", signals: [spi('MISO')], noBreadboard: true },
    {
      name: '5V.2',
      x: 154.1,
      y: 43.2,
      dir: "right",
      signals: [{ type: 'power', signal: 'VCC', voltage: 5 }],
      noBreadboard: true,
    },
    { name: '13.2', x: 163.7, y: 33.6, dir: "right", signals: [spi('SCK')], noBreadboard: true },
    {
      name: '11.2',
      x: 154.1,
      y: 33.6,
      dir: "right",
      signals: [spi('MOSI'), { type: 'pwm' }],
      noBreadboard: true,
    },
    { name: 'RESET.3', x: 163.7, y: 24, dir: "right", signals: [], noBreadboard: true },
    {
      name: 'GND.3',
      x: 154.1,
      y: 24,
      dir: "right",
      signals: [{ type: 'power', signal: 'GND' }],
      noBreadboard: true,
    },
  ]
//   [
//     // Digital Pins (ညာဘက်အပေါ်)
//     { id: 'D0', x: 256, y: 14 ,side: "top" }, { id: 'D1', x: 246, y: 14,side: "top" }, { id: 'D2', x: 236, y: 14,side: "top" },
//     { id: 'D3', x: 226, y: 14 ,side: "top"}, { id: 'D4', x: 216, y: 14,side: "top"}, { id: 'D5', x: 206, y: 14 ,side: "top"},
//     { id: 'D6', x: 196, y: 14 ,side: "top"}, { id: 'D7', x: 188, y: 14,side: "top"}, { id: 'D8', x: 172, y: 14,side: "top"},
//     { id: 'D9', x: 162, y: 14 ,side: "top"}, { id: 'D10', x: 152, y: 14,side: "top"}, { id: 'D11', x: 142, y: 14,side: "top"},
//     { id: 'D12', x: 132, y: 14 ,side: "top"}, { id: 'D13', x: 124, y: 14 ,side: "top"}, { id: 'GND1', x: 114, y: 14 ,side: "top"},
//     { id: 'AREF', x: 104, y: 14 ,side: "top"},{ id: 'GND2', x: 96, y: 14 ,side: "top"},{ id: 'GND3', x: 86, y: 14 ,side: "top"},
//     // Power & Analog (ဘယ်ဘက်အောက်)
//     { id: 'GND', x: 120, y: 194 ,side: "bottom" },{ id: 'IDREF', x: 130, y: 194 ,side: "bottom" },
//     { id: 'RESET', x: 140, y: 194 ,side: "bottom" }, { id: '3V3', x: 148, y: 194 ,side: "bottom" }, { id: '5V', x: 158, y: 194 ,side: "bottom" },
//     { id: 'GND4', x: 168, y: 194 ,side: "bottom" }, { id: 'GND5', x: 178, y: 194 ,side: "bottom" }, { id: 'VIN', x: 188, y: 194 ,side: "bottom" },
//     { id: 'A0', x: 206, y: 194 ,side: "bottom" }, { id: 'A1', x: 216, y: 194 ,side: "bottom" }, { id: 'A2', x: 226, y: 194 ,side: "bottom" }, 
//     { id: 'A3', x: 236, y: 194 ,side: "bottom" }, { id: 'A4', x: 246, y: 194 ,side: "bottom" }, { id: 'A5', x: 256, y: 194 ,side: "bottom" },
//   ]