import { analog, i2c, spi, usart } from './pin';

export const ARDUINO_NANO_PIN= 
  [
    { name: 'D12', x: 19.7, y: 4.8, dir: "top", signals: [spi('MISO')] },
    { name: 'D11', x: 29.3, y: 4.8, dir: "top", signals: [spi('MOSI'), { type: 'pwm' }] },
    { name: 'D10', x: 38.9, y: 4.8, dir: "top", signals: [spi('SS'), { type: 'pwm' }] },
    { name: 'D9', x: 48.5, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: 'D8', x: 58.1, y: 4.8, dir: "top", signals: [] },
    { name: 'D7', x: 67.7, y: 4.8, dir: "top", signals: [] },
    { name: 'D6', x: 77.3, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: 'D5', x: 86.9, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: 'D4', x: 96.5, y: 4.8, dir: "top", signals: [] },
    { name: 'D3', x: 106.1, y: 4.8, dir: "top", signals: [{ type: 'pwm' }] },
    { name: 'D2', x: 115.7, y: 4.8, dir: "top", signals: [] },
    { name: 'GND.2', x: 125.3, y: 4.8, dir: "top", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'RESET.2', x: 134.9, y: 4.8, dir: "top", signals: [] },
    { name: 'D0', x: 144.5, y: 4.8, dir: "top", signals: [usart('TX')] },
    { name: 'D1', x: 154.1, y: 4.8, dir: "top", signals: [usart('RX')] },
    { name: 'D13', x: 19.7, y: 62.4, dir: "bottom", signals: [spi('SCK')] },
    { name: '3.3V', x: 29.3, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 3.3 }] },
    { name: 'AREF', x: 38.9, y: 62.4, dir: "bottom", signals: [] },
    { name: 'A0', x: 48.5, y: 62.4, dir: "bottom", signals: [analog(0)] },
    { name: 'A1', x: 58.1, y: 62.4, dir: "bottom", signals: [analog(1)] },
    { name: 'A2', x: 67.7, y: 62.4, dir: "bottom", signals: [analog(2)] },
    { name: 'A3', x: 77.3, y: 62.4, dir: "bottom", signals: [analog(3)] },
    { name: 'A4', x: 86.9, y: 62.4, dir: "bottom", signals: [analog(4), i2c('SDA')] },
    { name: 'A5', x: 96.5, y: 62.4, dir: "bottom", signals: [analog(5), i2c('SCL')] },
    { name: 'A6', x: 106.1, y: 62.4, dir: "bottom", signals: [analog(6)] },
    { name: 'A7', x: 115.7, y: 62.4, dir: "bottom", signals: [analog(7)] },
    { name: '5V', x: 125.3, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC', voltage: 5 }] },
    { name: 'RESET', x: 134.9, y: 62.4, dir: "bottom", signals: [] },
    { name: 'GND.1', x: 144.5, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'GND' }] },
    { name: 'VIN', x: 154.1, y: 62.4, dir: "bottom", signals: [{ type: 'power', signal: 'VCC' }] },

    { name: '12.2', x: 163.7, y: 43.2, dir: "right", signals: [spi('MISO')], noBreadboard: true },
    {
      name: '5V.2',
      x: 154.1,
      y: 43.2,
      dir: "right",
      signals: [{ type: 'power', signal: 'VCC', voltage: 5 }],
      noBreadboard: true,
    },
    { name: '13.2', x: 163.7, y: 33.6, dir: "right", signals: [spi('SCK')], noBreadboard: true },
    {
      name: '11.2',
      x: 154.1,
      y: 33.6,
      dir: "right",
      signals: [spi('MOSI'), { type: 'pwm' }],
      noBreadboard: true,
    },
    { name: 'RESET.3', x: 163.7, y: 24, dir: "right", signals: [], noBreadboard: true },
    {
      name: 'GND.3',
      x: 154.1,
      y: 24,
      dir: "right",
      signals: [{ type: 'power', signal: 'GND' }],
      noBreadboard: true,
    },
  ]
